### PR TITLE
Updated to newer logo. We dropped the drip!

### PR DESCRIPTION
**Pull request by robertericreeves**
Thanks!

### CODE REVIEW

**Comment by adriens** [comment]
Yes, thanks a lot ! I'll generate a new CDN so it will available for the next Choco Release 👏

**Comment by adriens** [comment]
https://cdn.statically.io/gh/adriens/chocolatey-liquibase/master/liquibase.png

**Comment by adriens** [comment]
For the current #9 it won't operate, but for the next one it will be deployed 👍

**Comment by robertericreeves** [comment]
Thanks!

**Pull request merged**
